name: Check for exposed secrets in the PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  fetch_code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo PR Changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=$(echo "${{ github.event.pull_request.number }}")
          pip install PyGithub
          python - <<EOF > changes.txt
          from github import Github
          g = Github("${{ secrets.PAT_TOKEN }}")
          repo = g.get_repo("${{ github.repository }}")
          pr = repo.get_pull(${PR_NUMBER})
          files = pr.get_files()
          f = open("code.txt", "w")
          for file in files:
              f.write(f"Changes in file {file.filename}:")
              f.write(file.patch)
          f.close()
          EOF
      - name: Send Slack alert
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        run: |
          python regex.py code.txt
          python alerter.py $SLACK_WEBHOOK_URL output.txt ${{ github.repository }} ${{ github.event.pull_request.number }}


